rails_projects/ecommerce_app/config/routes.rb
Rails.application.routes.draw do

  root 'shop_categories#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :shop_categories, shallow: true do
    resources :product_categories
  end

  resources :users do
    resources :shops, :products
  end

  

end

rails_projects/ecommerce_app/app/models/user.rb
class User
  include MongoMapper::Document
  include Geocoder::Model::MongoMapper
  include ActiveModel::SecurePassword

  key :name, String,  :length => { :in => 3..15 }, :unique => true, :required => true
  key :email, String
  key :address, String,   :length => { :in => 3..50 }, :required => true
  key :phone, String,   :length => { :in => 10..20 }, :required => true
  key :password, String,  :length => { :in => 6..25 }
  key :password_digest, String
  key :remember_token, String
  key :active, Boolean
  key :admin, Boolean 
  key :coordinates, :type => Array
  key :location, :type => Hash

  before_create :create_remember_token
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
 
  timestamps!
  has_secure_password

  geocoded_by :address, :skip_index => true    # can also be an IP address
  after_validation :geocode, :if => :address_changed?
#  before_save self.location = {type: "Point", coordinates: self.coordinates}

  one :shop, dependent: :destroy
  many :products, dependent: :destroy
  many :orders, dependent: :destroy

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
  
end

rails_projects/ecommerce_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:show, :edit, :update, :destroy, :index, :office]
  before_action :correct_user,   only: [:show, :edit, :update, :destroy, :office]
  before_action :admin_user,     only: [:destroy, :office]
  before_action :active_user,    only: :office

  # GET /users
  # GET /users.json
  def index # Used for list of favorites or followers/followings list
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json

  def show
    @user = User.find(params[:id])
    if @user.active?
      @shop = @user.shop
      render action: "active_show"
    end
  end

# def show
#   @book = Book.find(params[:id])
#   if @book.special?
#     render action: "special_show" and return
#   end
#   render action: "regular_show"
# end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :address, :phone, :password, :password_confirmation, :active)
    end
    # Used in place of set_user - default setup
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    # Admin access to edit shops
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end    
    # Only shop admin user can edit their shop
    def active_user
      redirect_to(root_url) unless current_user.active?
    end

end

rails_projects/ecommerce_app/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

rails_projects/ecommerce_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/ecommerce_app/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rails_projects/ecommerce_app/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

rails_projects/ecommerce_app/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

rails_projects/ecommerce_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
'Links'
[favorites, followers#, followings#, reservations#, orders#, profile]

'Jquery'
[#microposts(inbox/outbox)]

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit Profile', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%= link_to "Sign out", signout_path, method: "delete"  %> 