rails_projects/ecommerce_app/config/routes.rb
Rails.application.routes.draw do

  root 'shop_categories#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :shop_categories, shallow: true do
    resources :product_categories
  end

  resources :users do
    resources :shops, :products
  end

  

end

rails_projects/ecommerce_app/app/models/shop.rb
class Shop
  include MongoMapper::EmbeddedDocument

  key :user_id,  ObjectId
  key :shop_category, Array,  :length => { :in => 1..5 }
  key :shop_title, String,    :length => { :in => 3..20 }
  key :shop_banner, String
  key :shop_info, String,   :length => { :in => 20..200 }
  key :shop_about, String,    :length => { :in => 20..300 }
  key :shop_hours, String
  key :shop_phone, String
  key :shop_url, String  
  key :shop_gallery, String
  key :shop_slug, String  
  timestamps!

  belongs_to :user
end

rails_projects/ecommerce_app/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
#  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  before_action :signed_in_user, only: [:new, :edit, :update, :destroy]
#  before_action :correct_user,   only: [:edit, :update, :destroy, :office]
  # GET /shops
  # GET /shops.json
  def index # the search page?
    @user = User.find(params[:user_id])
    @shop = @user.shop
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @user = User.where('shop._id' => BSON::ObjectId.from_string(params[:id])).first
    @shop = User.where('shop._id' => BSON::ObjectId.from_string(params[:id]))
      .map do |s|  s.products.select { |p| p._id == BSON::ObjectId.from_string(params[:id]) } end.flatten    
  end

  # GET /shops/new
  def new
    @user = User.find(params[:user_id])
    @shop = @user.shop.build if signed_in?
  end

  # GET /shops/1/edit
  def edit
    @user = User.where('shop._id' => BSON::ObjectId.from_string(params[:id])).first
    @shop = @user.shop.select { |p| p._id == BSON::ObjectId.from_string(params[:id]) }
  end

  # POST /shops
  # POST /shops.json
  def create
    @user = User.find(params[:user_id])
    @shop = @user.shop.build(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    @user = User.where('shop._id' => BSON::ObjectId.from_string(params[:id])).first
    @shop = @user.shop.select { |p| p._id == BSON::ObjectId.from_string(params[:id]) }

    respond_to do |format|
      if @shop.update_attributes(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @user = User.where('shop._id' => BSON::ObjectId.from_string(params[:id])).first
    @user.shop.delete_if {|p| p._id == BSON::ObjectId.from_string(params[:id]) }

    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:shop_title, :shop_info, :shop_category, :shop_banner, :shop_about, :shop_hours, :shop_url, :shop_gallery, :shop_slug)
    end
end

rails_projects/ecommerce_app/app/helpers/shops_helper.rb
module ShopsHelper
end

rails_projects/ecommerce_app/app/views/shops/_form.html.erb
<%= form_for[@shop, @user] do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shop_title %><br>
    <%= f.text_field :shop_title %>
  </div>
  <div class="field">
    <td><%= f.label :shop_category_industry %></td>
    <td><%= f.collection_select :shop_category, ShopCategory.all, :id, :full_line, prompt: true %></td>
  </div>
  <div class="field">
    <%= f.label :shop_banner %><br>
    <%= f.file_field :shop_banner %>
  </div>
    <div class="field">
    <%= f.label :shop_info %><br>
    <%= f.text_area :shop_info %>
  </div>
    <div class="field">
    <%= f.label :shop_about %><br>
    <%= f.text_area :shop_about %>
  </div>
    <div class="field">
    <%= f.label :shop_hours %><br>
    <%= f.time_field :shop_hours %>
  </div>
    <div class="field">
    <%= f.label :shop_url %><br>
    <%= f.url_field :shop_url %>
  </div>
    <div class="field">
    <%= f.label :shop_gallery %><br>
    <%= f.file_field :shop_gallery %>
  </div>
    <div class="field">
    <%= f.label :shop_slug %><br>
    <%= f.text_field :shop_slug %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/ecommerce_app/app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

rails_projects/ecommerce_app/app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
<h1>Listing shops</h1>
  <thead>
    <tr>
      <th>Shop title</th>
      <th>Shop banner</th>
      <th>Shop info</th>
      <th>Shop about</th>
      <th>Shop hours</th>
      <th>Shop url</th>
      <th>Shop gallery</th>
      <th>Shop slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.shop_title %></td>
        <td><%= shop.shop_banner %></td>
        <td><%= shop.shop_info %></td>
        <td><%= shop.shop_about %></td>
        <td><%= shop.shop_hours %></td>
        <td><%= shop.shop_url %></td>
        <td><%= shop.shop_gallery %></td>
        <td><%= shop.shop_slug %></td>
        <td><%= link_to 'Show', shop %></td>

      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

<br>

rails_projects/ecommerce_app/app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

rails_projects/ecommerce_app/app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop title:</strong>
  <%= @shop.shop_title %>
</p>
<p>
  <strong>Shop banner:</strong>
  <%= image_tag @shop.shop_banner %>
</p>
<p>
  <strong>Shop Menu:</strong>
  <%= link_to 'Menu', shop_products_path(@shop) %>
</p>
<p>
  <strong>Follow Shop :</strong>
  <%= 'follow link here' %>
</p>
<p>
  <strong>Reservation:</strong>
  <%= 'make reservation link here' %>
</p>
<p>
  <strong>Rate Shop:</strong>
  <%= 'rate shop link' %>
</p>
<p>
  <strong>Shop Address:</strong>
  <%= 'from user address' %>
</p>
<p>
  <strong>Shop info:</strong>
  <%= @shop.shop_info %>
</p>
<p>
  <strong>Shop about:</strong>
  <%= @shop.shop_about %>
</p>
<p>
  <strong>Shop hours:</strong>
  <%= @shop.shop_hours %>
</p>
<p>
  <strong>Shop url:</strong>
  <%= @shop.shop_url %>
</p>
<p>
  <strong>Shop gallery:</strong>
  <%= @shop.shop_gallery %>
</p>
<p>
  <strong>Shop slug:</strong>
  <%= @shop.shop_slug %>
</p>
<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>