rails_projects/ecommerce_app/config/routes.rb
Rails.application.routes.draw do

  root 'shop_categories#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :shop_categories, shallow: true do
    resources :product_categories
  end

  resources :users do
    resources :shops, :products
  end

  

end

rails_projects/ecommerce_app/app/models/shop_category.rb
VALID_CATEGORY_REGEX = /\A[[:alpha:]]+\z/i

class ShopCategory
  include MongoMapper::Document

  key :industry,    String, :length => { :in => 1..25 }
  key :segment,     String, :length => { :in => 1..25 }
  key :specialty,   String, :length => { :in => 1..25 }
  key :product_type, String, :length => { :in => 1..25 }
  key :other,       String, :length => { :in => 1..25 }

#  validates :industry, :segment, :specialty, :product_type, :other, presence: true, format: { with: VALID_CATEGORY_REGEX }, uniqueness: { case_sensitive: false }
#  before_save { self.industry = industry.downcase, self.segment = segment.downcase, self.specialty = specialty.downcase, self.product_type = product_type.downcase, self.other = other.downcase }
  timestamps!
#  userstamps!
  many :product_categories, dependent: :destroy


  def full_line
    "#{industry} || #{segment} || #{specialty} || #{product_type} || #{other}"
  end
end  

#form for categoryies
# website > http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_select
#<%= f.label :project_id %>
#<%= f.collection_select :project_id, Project.all, :id, :name %>

#object.collection_select :attribute, Pull.all, :id, :description - my own english
#collection_select(object, method, collection, value_method, text_method, options = {}, html_options = {}) 
#collection_select(:post, :author_id, Author.all, :id, :name_with_initial, prompt: true)


#grouped_collection_select(object, method, collection, group_method, group_label_method, option_key_method, option_value_method, options = {}, html_options = {}) 
#grouped_collection_select(:city, :country_id, @continents, :countries, :name, :id, :name)

#grouped_options_for_select(grouped_options, selected_key = nil, options = {})
#Ex. ["North America",[["United States","US"],["Canada","CA"]]]

#option_groups_from_collection_for_select(collection, group_method, group_label_method, option_key_method, option_value_method, selected_key = nil) 
#option_groups_from_collection_for_select(@continents, :countries, :name, :id, :name, 3)

rails_projects/ecommerce_app/app/controllers/shop_categories_controller.rb
class ShopCategoriesController < ApplicationController
#  before_action :set_shop_category, only: [:show, :edit, :update, :destroy]
#  before_action :set_shop_categories, only: [:index, :new, :create]

  # GET /shop_categories
  # GET /shop_categories.json
  def index
    @shop_categories = ShopCategory.all    
  end

  # GET /shop_categories/1
  # GET /shop_categories/1.json
  def show
    @shop_category = ShopCategory.find(params[:id])
    @product_categories = @shop_category.product_categories
  end

  # GET /shop_categories/new
  def new
    @shop_category = ShopCategory.build if signed_in?
    @shop_categories = ShopCategory.all
  end

  # GET /shop_categories/1/edit
  def edit
    @shop_category = ShopCategory.find(params[:id])
    @shop_categories = ShopCategory.all   
  end

  # POST /shop_categories
  # POST /shop_categories.json

  def create
    @shop_category = ShopCategory.new(shop_category_params)

    respond_to do |format|
      if @shop_category.save
        format.html { redirect_to @shop_category, notice: 'Shop category was successfully created.' }
        format.json { render :show, status: :created, location: @shop_category }
      else
        format.html { render :new }
        format.json { render json: @shop_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_categories/1
  # PATCH/PUT /shop_categories/1.json
  def update
    @shop_category = ShopCategory.find(params[:id])
    respond_to do |format|
      if @shop_category.update_attributes(shop_category_params)
        format.html { redirect_to @shop_category, notice: 'Shop category was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_category }
      else
        format.html { render :edit }
        format.json { render json: @shop_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_categories/1
  # DELETE /shop_categories/1.json
  def destroy
    @shop_category = ShopCategory.find(params[:id])
    @shop_category.destroy
    respond_to do |format|
      format.html { redirect_to shop_categories_url, notice: 'Shop category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_category_params
      params.require(:shop_category).permit(:industry, :segment, :specialty, :product_type, :other)
    end
end

rails_projects/ecommerce_app/app/views/shop_categories/_form.html.erb
<%= form_for(@shop_category) do |f| %>
  <% if @shop_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_category.errors.count, "error") %> prohibited this shop_category from being saved:</h2>

      <ul>
      <% @shop_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :segment %><br>
    <%= f.text_field :segment %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br>
    <%= f.text_field :specialty %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/ecommerce_app/app/views/shop_categories/edit.html.erb
<h1>Editing shop_category</h1>
<h2> Shop Categories </h2>

<% if @shop_categories %>
<%= render 'shared/shop_categories_index' %>
<% end %>

<h2> Edit Shop Category </h2>
<%= render 'form' %>

<%= link_to 'Show', @shop_category %> |
<%= link_to 'Back', shop_categories_path %>

rails_projects/ecommerce_app/app/views/shop_categories/index.html.erb
<h1>Listing shop_categories</h1>

<% if @shop_categories %>
<%= render 'shared/shop_categories_index' %>
<% else %>
<%= No Shop Categories In Database %>
<% end %>

<br>

<%= link_to 'New Shop category', new_shop_category_path %>

rails_projects/ecommerce_app/app/views/shop_categories/new.html.erb
<h1>A new shop category?</h1>

<h2> Shop Categories </h2>

<% if @shop_categories %>
<%= render 'shared/shop_categories_index' %>
<% end %>

<h2> Create New Shop Category </h2>
<%= render 'form' %>

<%= link_to 'Back', shop_categories_path %>

rails_projects/ecommerce_app/app/views/shop_categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">

<h2> Shop Category </h2>
      <%= render 'shared/shop_category_show' %>

<h2> Product Categories </h2>
      <%= render 'shared/product_categories_index' %>

    </table>      
  </div>
</div>

<%= link_to 'Add a new Product Category', new_shop_category_product_category_path(@shop_category) %> #clashes with edit form.

<section>
<h2> Create a New Product Category </h2>

    <%= render 'shared/form_new_product_category' %>

</section>

<%= link_to 'Back', shop_categories_path %>