rails_projects/ecommerce_app/config/routes.rb
Rails.application.routes.draw do

  root 'shop_categories#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :shop_categories, shallow: true do
    resources :product_categories
  end

  resources :users do
    resources :shops, :products
  end

  

end

rails_projects/ecommerce_app/app/models/product_category.rb
class ProductCategory
  include MongoMapper::EmbeddedDocument

  key :shop_category_id,  ObjectId
  key :product_group,     String, :length => { :in => 0..25 }
  key :product_subgroup,  String, :length => { :in => 0..25 }
  key :product_type,      String, :length => { :in => 0..25 }
  key :product_gender,    String, :length => { :in => 0..25 }
  key :other_product_category,     String, :length => { :in => 0..25 }
  key :product_size, Array, :length => { :in => 0..25 }
  key :product_box_size, Array, :length => { :in => 0..25 }
  key :product_bottle_size, Array, :length => { :in => 0..25 }
  key :product_pack_size, Array, :length => { :in => 0..25 }
  key :product_service_time, Array, :length => { :in => 0..25 }
  key :product_color, Array, :length => { :in => 0..25 }
  key :other, Array, :length => { :in => 0..25 }
#  validates :product_group, :product_subgroup, :product_type, :product_gender, 
#    presence: true, format: { with: VALID_CATEGORY_REGEX }, uniqueness: { case_sensitive: false }
  
  timestamps!
#  userstamps!

  embedded_in :shop_category

  def full_line
    "#{product_group} || #{product_subgroup} || #{product_type} || #{product_gender} || #{other_product_category}
    #{product_size} || #{product_box_size} || #{product_bottle_size} || #{product_pack_size} || #{product_service_time}
    #{product_color} || #{other}"
  end
end

rails_projects/ecommerce_app/app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
#  before_action :set_shop_category, only: [:new, :create]
#  before_action :set_product_category, only: [:show, :edit, :update, :destroy]
#  before_action :set_product_categories, only: [:index]
  # GET /product_categories
  # GET /product_categories.json
  def index
    @shop_category = ShopCategory.where('product_categories._id' => BSON::ObjectId.from_string(params[:id])).first
    @product_categories = @shop_categories.product_categories
  end

  # GET /product_categories/1
  # GET /product_categories/1.json
  def show
    
#    @product_category = ProductCategory.find(params[:id])
#    @product_category = ShopCategory.find("product_categories._id" => BSON::ObjectId.from_string(params[:id]))
#    @product_category = ShopCategory.find('product_categories._id' => params[:id])
    @shop_category = ShopCategory.where('product_categories._id' => BSON::ObjectId.from_string(params[:id])).first
#    @product_category = ShopCategory.product_categories.where(:_id => BSON::ObjectId.from_string(params[:id])).first
#    @product_category = ShopCategory.where('product_categories._id' => params[:id]).first
#    @product_categry = ShopCategory.all(:conditions => {'product_categories.id' => BSON::ObjectId.from_string(params[:id])})
#    @product_category = ShopCategory.find( { product_categories: {id: params[:id]} } )
#    @product_category = ShopCategory.find_by_product_categories_id(params[:id])
#    @product_variations = @product_category.product_variations
#    @product_options = @product_category.product_options
#    @product_category.product_categories.each { |key, value| shop_category_id = @value }
#    @shop_category = ShopCategory.find(:shop_category_id)

    @product_category = ShopCategory.where('product_categories._id' => BSON::ObjectId.from_string(params[:id]))
      .map do |sc|  sc.product_categories.select { |pc| pc._id == BSON::ObjectId.from_string(params[:id]) } end.flatten

  end

  # GET /product_categories/new
  def new
    @shop_category = ShopCategory.find(params[:shop_category_id])
    @product_category = @shop_category.product_categories.build if signed_in?
  end

  # GET /product_categories/1/edit
  def edit
    @shop_category = ShopCategory.where('product_categories._id' => BSON::ObjectId.from_string(params[:id])).first
#    @product_category = ProductCategory.find(params[:id])
    @product_category = @shop_category.product_categories.select { |pc| pc._id == BSON::ObjectId.from_string(params[:id]) }#.each { |b| b.address = new_address }
#    @product_category = ShopCategory.where('product_categories._id' => BSON::ObjectId.from_string(params[:id]))
#      .map do |sc|  sc.product_categories.select { |pc| pc._id == BSON::ObjectId.from_string(params[:id]) } end.flatten 
    @product_categories = @shop_category.product_categories

  end

  # POST /product_categories
  # POST /product_categories.json
  def create
    @shop_category = ShopCategory.find(params[:shop_category_id])
    @product_category = @shop_category.product_categories.build(product_category_params)
#    @product_category.shop_category = @shop_category

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to @shop_category, notice: 'Product category was successfully created.' }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new }
        format.json { render json: @shop_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1
  # PATCH/PUT /product_categories/1.json
  def update
    @shop_category = ShopCategory.where('product_categories._id' => BSON::ObjectId.from_string(params[:id])).first
    @product_category = @shop_category.product_categories.select { |pc| pc._id == BSON::ObjectId.from_string(params[:id]) }
    respond_to do |format|
        @product_category.each do |product_category|
      if product_category.update_attributes(product_category_params)
        format.html { redirect_to @shop_category, notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit }
        format.json { render json: @shop_category.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /product_categories/1
  # DELETE /product_categories/1.json
  def destroy
    @shop_category = ShopCategory.where('product_categories._id' => BSON::ObjectId.from_string(params[:id])).first
#    @product_category = @shop_category.product_categories.select { |pc| pc._id == BSON::ObjectId.from_string(params[:id]) }
#    @product_category.clear
    @shop_category.product_categories.delete_if {|pc| pc._id == BSON::ObjectId.from_string(params[:id]) }
    respond_to do |format|
      format.html { redirect_to @shop_category, notice: 'Product category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_category_params
      params.require(:product_category).permit(:shop_category_id, :product_group, :product_subgroup, :product_type, 
        :product_gender, :other_product_category, :product_size, :product_box_size, :product_bottle_size, 
        :Product_pack_size, :product_service_time, :product_color, :other)
    end
end

rails_projects/ecommerce_app/app/views/product_categories/_form.html.erb
<%= form_for (@product_category) do |f| %>
  <% if @shop_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_category.errors.count, "error") %> prohibited this product_category from being saved:</h2>

      <ul>
      <% @shop_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_group %><br>
    <%= f.text_field :product_group %>
  </div>
  <div class="field">
    <%= f.label :product_subgroup %><br>
    <%= f.text_field :product_subgroup %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :product_gender %><br>
    <%= f.text_field :product_gender %>
  </div>
  <div class="field">
    <%= f.label :other_product_category %><br>
    <%= f.text_field :other_product_category %>
  </div>

  <div class="field">
    <%= f.label :product_size %><br>
    <%= f.text_field :product_size %>
  </div>
  <div class="field">
    <%= f.label :product_pack_size %><br>
    <%= f.text_field :product_pack_size %>
  </div>
  <div class="field">
    <%= f.label :product_box_size %><br>
    <%= f.text_field :product_box_size %>
  </div>
  <div class="field">
    <%= f.label :product_bottle_size %><br>
    <%= f.text_field :product_bottle_size %>
  </div>
  <div class="field">
    <%= f.label :product_service_time %><br>
    <%= f.text_field :product_service_time %>
  </div>
  <div class="field">
    <%= f.label :product_color %><br>
    <%= f.text_field :product_color %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/ecommerce_app/app/views/product_categories/edit.html.erb
<h1>Editing product_category</h1>
<h2> Product Categories </h2>
<%= render 'shared/product_categories_index' %>

<h2> Edit Product Category </h2>
<%= render 'form' %>

<%= link_to 'Show', @product_category %> |
<%= link_to 'Back', product_category_path %>

rails_projects/ecommerce_app/app/views/product_categories/index.html.erb
<h1>Listing product_categories</h1>

<%= render 'shared/product_categories_index' %>

<br>

<%= link_to 'New Product category', new_shop_category_product_category_path %>

rails_projects/ecommerce_app/app/views/product_categories/new.html.erb
<h1>New Product Category</h1>

<h2> Product Categories </h2>
<%= render 'shared/product_categories_index' %>

<h2> Create New Product Category </h2>
<%= render 'form' %>

<%= link_to 'Back', shop_category_product_categories_path %>

rails_projects/ecommerce_app/app/views/product_categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">

<h2> Shop Category </h2>
    <%= render 'shared/shop_category_show' %>

<h2> Product Category </h2>
    <%= render 'shared/product_category_show' %>


    </table>
  </div>
</div>


<%= link_to 'Edit Shop Category', edit_shop_category_path(@shop_category) %> ||
<%= link_to 'Back', shop_category_path(@shop_category) %>
 